
export const TYPES = {
    // Repositories
    StudentRepository: Symbol.for('StudentRepository'),
    CompanyRepository: Symbol.for('CompanyRepository'),
    AdminRepository: Symbol.for('AdminRepository'),
    CompanyEmployeeRepository: Symbol.for('CompanyEmployeeRepository'),
    EmployeeRepository: Symbol.for('EmployeeRepository'),
    TeacherRepository: Symbol.for('TeacherRepository'),
    OtpRepository: Symbol.for('OtpRepository'),
    CourseRepository: Symbol.for('CourseRepository'),
    SubscriptionPlanRepository: Symbol.for('SubscriptionPlanRepository'),
    WishlistRepository: Symbol.for('WishlistRepository'),
    CartRepository: Symbol.for('CartRepository'),
    OrderRepository: Symbol.for('OrderRepsitory'),
    CompanyOrderRepository: Symbol.for('CompanyOrderRepsitory'),
    TeacherAvailabilityRepository: Symbol.for('TeacherAvailabilityRepository'),
    StudentBookingRepository: Symbol.for('StudentBookingRepository'),
    ChatRepository: Symbol.for('ChatRepository'),
    NotificationRepository: Symbol.for('NotificationRepository'),


    // Services
    StudentAuthService: Symbol.for('StudentAuthService'),
    StudentProfileService: Symbol.for('StudentProfileService'),
    StudentCourseService: Symbol.for('StudentCourseService'),
    StudentWishlistService: Symbol.for('StudentWishlistService'),
    StudentCartService: Symbol.for('StudentCartService'),
    StudentSubscriptionService: Symbol.for('StudentSubscriptionService'),
    StudentBookingService: Symbol.for('StudentBookingService'),
    StudentPurchaseService: Symbol.for('StudentPurchaseService'),
    StudentTeacherService: Symbol.for('StudentTeacherService'),
    CompanyAuthService: Symbol.for('CompanyAuthService'),
    CompanyEmployeeService: Symbol.for('CompanyEmployeeService'),
    CompanyProfileService: Symbol.for('CompanyProfileService'),
    CompanySubscriptionService: Symbol.for('CompanySubscriptionService'),
    CompanyCourseService: Symbol.for('CompanyCourseService'),
    CompanyWishlistService: Symbol.for('CompanyWishlistService'),
    CompanyCartService: Symbol.for('CompanyCartService'),
    CompanyPurchaseService: Symbol.for('CompanyPurchaseService'),


    AdminAuthService: Symbol.for('AdminAuthService'),
    AdminStudentService: Symbol.for('AdminStudentService'),
    AdminTeacherService: Symbol.for('AdminTeacherService'),
    AdminCourseService: Symbol.for('AdminCourseService'),
    AdminCompanyService: Symbol.for('AdminCompanyService'),
    AdminEmployeeService: Symbol.for('AdminEmployeeService'),
    AdminOrderService: Symbol.for('AdminOrderService'),
    AdminSubscriptionPlanService: Symbol.for('AdminSubscriptionPlanService'),
    EmployeeAuthService: Symbol.for('EmployeeAuthService'),
    TeacherAuthService: Symbol.for('TeacherAuthService'),
    TeacherProfileService: Symbol.for('TeacherProfileService'),
    TeacherAvailabilityService: Symbol.for('TeacherAvailabilityService'),
    TeacherCourseService: Symbol.for('TeacherCourseService'),
    TeacherCallRequestService: Symbol.for('TeacherCallRequestService'),
    CourseService: Symbol.for('CourseService'),
    SubscriptionPlanService: Symbol.for('SubscriptionPlanService'),

    EmployeeProfileService: Symbol.for('EmployeeProfileService'),
    EmployeeCompanyService: Symbol.for('EmployeeCompanyService'),
    EmployeeCourseService: Symbol.for('EmployeeCourseService'),
    
    ChatService: Symbol.for('ChatService'),

    // Controllers
    StudentAuthController: Symbol.for('StudentAuthController'),
    StudentCourseController: Symbol.for('StudentCourseController'),
    StudentProfileController: Symbol.for('StudentProfileController'),
    StudentWishlistController: Symbol.for('StudentWishlistController'),
    StudentCartController: Symbol.for('StudentCartController'),
    StudentSubscriptionController: Symbol.for('StudentSubscriptionController'),
    StudentPurchaseController: Symbol.for('StudentPurchaseController'),
    StudentBookingController: Symbol.for('StudentBookingController'),
    StudentTeacherController: Symbol.for('StudentTeacherController'),
    CompanyAuthController: Symbol.for('CompanyAuthController'),
    CompanyProfileController: Symbol.for('CompanyProfileController'),
    CompanyEmployeeController: Symbol.for('CompanyEmployeeController'),
    CompanyCourseController: Symbol.for('CompanyCourseController'),
    CompanySubscriptionController: Symbol.for('CompanySubscriptionController'),
    CompanyWishlistController: Symbol.for('CompanyWishlistController'),
    CompanyCartController: Symbol.for('CompanyCartController'),
    CompanyPurchaseController: Symbol.for('CompanyPurchaseController'),


    AdminAuthController: Symbol.for('AdminAuthController'),
    AdminCourseController: Symbol.for('AdminCourseController'),
    AdminTeacherController: Symbol.for('AdminTeacherController'),
    AdminStudentController: Symbol.for('AdminStudentController'),
    AdminCompanyController: Symbol.for('AdminCompanyController'),
    AdminOrderController: Symbol.for('AdminOrderController  '),
    AdminEmployeeController: Symbol.for('AdminEmployeeController'),
    AdminSubscriptionPlanController: Symbol.for('AdminSubscriptionPlanController'),
    TeacherAuthController: Symbol.for('TeacherAuthController'),
    TeacherCourseController: Symbol.for('TeacherCourseController'),
    TeacherProfileController: Symbol.for('TeacherProfileController'),
    TeacherAvailabilityController: Symbol.for('TeacherAvailabilityController'),
    TeacherCallRequestController: Symbol.for('TeacherCallRequestController'),
    EmployeeAuthController: Symbol.for('EmployeeAuthController'),
    EmployeeProfileController: Symbol.for('EmployeeProfileController'),
    EmployeeCompanyController: Symbol.for('EmployeeCompanyController'),
    
    EmployeeCourseController: Symbol.for('EmployeeCourseController'),
    ChatController: Symbol.for('ChatController'),
    StudentNotificationController: Symbol.for('StudentNotificationController'),
    StudentNotificationService: Symbol.for('StudentNotificationService'),
    StudentNotificationRepository: Symbol.for('StudentNotificationRepository'),
    SharedController: Symbol.for('SharedController'),



    NotificationService: Symbol.for('NotificationService'),
    NotificationController: Symbol.for('NotificationController'),
    TeacherChatService: Symbol.for('TeacherChatService'),
    TeacherChatController: Symbol.for('TeacherChatController'),
        
        
    
};
