
export const TYPES = {
    // Repositories
    StudentRepository: Symbol.for('StudentRepository'),
    CompanyRepository: Symbol.for('CompanyRepository'),
    AdminRepository: Symbol.for('AdminRepository'),
    CompanyEmployeeRepository: Symbol.for('CompanyEmployeeRepository'),
    EmployeeRepository: Symbol.for('EmployeeRepository'),
    TeacherRepository: Symbol.for('TeacherRepository'),
    OtpRepository: Symbol.for('OtpRepository'),
    CourseRepository: Symbol.for('CourseRepository'),
    SubscriptionPlanRepository: Symbol.for('SubscriptionPlanRepository'),
    // Services
    StudentAuthService: Symbol.for('StudentAuthService'),
    StudentProfileService: Symbol.for('StudentProfileService'),
    StudentCourseService: Symbol.for('StudentCourseService'),
    StudentSubscriptionService:Symbol.for('StudentSubscriptionService'),
    CompanyAuthService: Symbol.for('CompanyAuthService'),
    CompanyEmployeeService: Symbol.for('CompanyEmployeeService'),
    CompanyProfileService: Symbol.for('CompanyProfileService'),
    CompanySubscriptionService: Symbol.for('CompanySubscriptionService'),
    CompanyCourseService: Symbol.for('CompanyCourseService'),
    AdminAuthService: Symbol.for('AdminAuthService'),
    AdminStudentService : Symbol.for('AdminStudentService'),
    AdminTeacherService : Symbol.for('AdminTeacherService'),
    AdminCourseService : Symbol.for('AdminCourseService'),
    AdminCompanyService : Symbol.for('AdminCompanyService'),
    AdminEmployeeService : Symbol.for('AdminEmployeeService'),
    AdminSubscriptionPlanService : Symbol.for('AdminSubscriptionPlanService'),
    EmployeeAuthService: Symbol.for('EmployeeAuthService'),
    TeacherAuthService: Symbol.for('TeacherAuthService'),
    TeacherProfileService: Symbol.for('TeacherProfileService'),
    TeacherCourseService: Symbol.for('TeacherCourseService'),
    CourseService: Symbol.for('CourseService'),
    SubscriptionPlanService: Symbol.for('SubscriptionPlanService'),


    // Controllers
    StudentAuthController: Symbol.for('StudentAuthController'),
    StudentCourseController: Symbol.for('StudentCourseController'),
    StudentProfileController: Symbol.for('StudentProfileController'),
    StudentSubscriptionController: Symbol.for('StudentSubscriptionController'),
    CompanyAuthController: Symbol.for('CompanyAuthController'),
    CompanyProfileController: Symbol.for('CompanyProfileController'),
    CompanyEmployeeController: Symbol.for('CompanyEmployeeController'),
    CompanyCourseController: Symbol.for('CompanyCourseController'),
    CompanySubscriptionController: Symbol.for('CompanySubscriptionController'),
    AdminAuthController: Symbol.for('AdminAuthController'),
    AdminCourseController: Symbol.for('AdminCourseController'),
    AdminTeacherController: Symbol.for('AdminTeacherController'),
    AdminStudentController: Symbol.for('AdminStudentController'),
    AdminCompanyController: Symbol.for('AdminCompanyController'),
    AdminEmployeeController: Symbol.for('AdminEmployeeController'),
    AdminSubscriptionPlanController: Symbol.for('AdminSubscriptionPlanController'),
    TeacherAuthController: Symbol.for('TeacherAuthController'),
    TeacherCourseController: Symbol.for('TeacherCourseController'),
    TeacherProfileController: Symbol.for('TeacherProfileController'),
    EmployeeAuthController: Symbol.for('EmployeeAuthController')
};
